# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.0"
slug: example
description: Example add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"

---
name: "TFTP server"
description: "Simple tftp server"
version: "0.1.0"
slug: "tftp"
init: false
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
map:
  - share:rw
ports:
  69/udp: 69
image: "ghcr.io/chrispyduck/{arch}-addon-tftp"
options:
  message: "Starting..."
schema:
  message: "str?"